# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{web_service_documenter}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Langevin", "Stephen Schor", "Scott Taylor"]
  s.date = %q{2011-08-17}
  s.description = %q{Document your json web services}
  s.email = ["dan.langevin@lifebooker.com", "beholdthepanda@gmail.com", "scott@railsnewbie.com"]
  s.executables = ["web_service_documenter"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/web_service_documenter",
    "docs/.html",
    "docs/authenticate.html",
    "docs/authenticate/.html",
    "docs/clients.html",
    "docs/loot.html",
    "docs/users/1.html",
    "examples/lifebooker_docs.yml",
    "examples/web_services.yml",
    "lib/templates/service.html.erb",
    "lib/web_service_documenter.rb",
    "lib/web_service_documenter/helper.rb",
    "lib/web_service_documenter/service.rb",
    "lib/web_service_documenter/service_collection.rb",
    "lib/web_service_documenter/templates/index.html.erb",
    "lib/web_service_documenter/templates/service.html.erb",
    "spec/config/endpoints.yml",
    "spec/config/group_endpoints.yml",
    "spec/lib/service_collection_spec.rb",
    "spec/lib/service_spec.rb",
    "spec/lib/web_service_documenter_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_harness.rb",
    "spec/tmp/index.html",
    "spec/tmp/users/1.html",
    "web_service_documenter.gemspec"
  ]
  s.homepage = %q{http://github.com/LifebookerInc/web_service_documenter}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Document your json web services}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["= 3.0.9"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<multipart-post>, [">= 0"])
      s.add_runtime_dependency(%q<trollop>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<guard>, ["= 0.6.1"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, ["= 3.0.9"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<multipart-post>, [">= 0"])
      s.add_dependency(%q<trollop>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<guard>, ["= 0.6.1"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["= 3.0.9"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<multipart-post>, [">= 0"])
    s.add_dependency(%q<trollop>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<guard>, ["= 0.6.1"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

